execute_process(
  COMMAND ${CMAKE_COMMAND} -E make_directory ${TMP_DIR}/VisTrailsPlugin
  COMMAND ${CMAKE_COMMAND} -E copy ${SOURCE_DIR}/README ${TMP_DIR}/VisTrailsPlugin
  COMMAND ${CMAKE_COMMAND} -E copy ${BINARY_DIR}/gui/qt/${CMAKE_SHARED_LIBRARY_PREFIX}VisTrailsGUI${CMAKE_SHARED_LIBRARY_SUFFIX} ${TMP_DIR}/VisTrailsPlugin
  COMMAND ${CMAKE_COMMAND} -E copy ${BINARY_DIR}/capi/src/${CMAKE_SHARED_LIBRARY_PREFIX}VisTrails${CMAKE_SHARED_LIBRARY_SUFFIX} ${TMP_DIR}/VisTrailsPlugin
  COMMAND ${CMAKE_COMMAND} -E copy ${BINARY_DIR}/paraviewplugin/quazip/${CMAKE_SHARED_LIBRARY_PREFIX}vtquazip${CMAKE_SHARED_LIBRARY_SUFFIX} ${TMP_DIR}/VisTrailsPlugin
  COMMAND ${CMAKE_COMMAND} -E copy ${BINARY_DIR}/paraviewplugin/${CMAKE_SHARED_LIBRARY_PREFIX}VisTrailsPlugin${CMAKE_SHARED_LIBRARY_SUFFIX} ${TMP_DIR}/VisTrailsPlugin
  WORKING_DIRECTORY ${TMP_DIR})

execute_process(
  COMMAND ${CMAKE_COMMAND} -E tar cvfz ${bundle_name} ${TMP_DIR}/VisTrailsPlugin
  WORKING_DIRECTORY ${TMP_DIR})
