superbuild_add_project(rapidjson
  LICENSE_FILES
    license.txt
  DEPENDS cxx11
  CMAKE_ARGS
    -DBUILD_SHARED_LIBS:BOOL=${BUILD_SHARED_LIBS}
    -DENABLE_TESTING:BOOL=OFF
    -DRAPIDJSON_BUILD_DOC:BOOL=OFF
    -DRAPIDJSON_BUILD_EXAMPLES:BOOL=OFF
    -DRAPIDJSON_BUILD_TESTS:BOOL=OFF

    # Disable the `export(PACKAGE)`.
    -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY:BOOL=OFF
    -DCMAKE_EXPORT_PACKAGE_REGISTRY:BOOL=OFF)
