superbuild_add_project(rapidjson
  LICENSE_FILES
    license.txt
  SPDX_LICENSE_IDENTIFIER
    "MIT AND BSD-3-Clause AND JSON"
  SPDX_COPYRIGHT_TEXT
    "Copyright (C) 2015 THL A29 Limited, a Tencent company, and Milo Yip"
    "Copyright (c) 2006-2013 Alexander Chemeris" # msinttypes
    "Copyright (c) 2002 JSON.org" # JSON
  DEPENDS cxx11
  CMAKE_ARGS
    -DBUILD_SHARED_LIBS:BOOL=${BUILD_SHARED_LIBS}
    -DENABLE_TESTING:BOOL=OFF
    -DRAPIDJSON_BUILD_DOC:BOOL=OFF
    -DRAPIDJSON_BUILD_EXAMPLES:BOOL=OFF
    -DRAPIDJSON_BUILD_TESTS:BOOL=OFF

    # Disable the `export(PACKAGE)`.
    -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY:BOOL=OFF
    -DCMAKE_EXPORT_PACKAGE_REGISTRY:BOOL=OFF)
