superbuild_add_project(snappy
  CMAKE_ARGS
    -DSNAPPY_BUILD_TESTS:BOOL=OFF
    -DCMAKE_INSTALL_LIBDIR:STRING=lib
    -DCMAKE_INSTALL_NAME_DIR:PATH=<INSTALL_DIR>/lib
    -DSNAPPY_BUILD_BENCHMARKS:BOOL=OFF
    -DSNAPPY_INSTALL:BOOL=ON
)
