superbuild_add_project(tiff
  DEPENDS
    zlib
  DEPENDS_OPTIONAL
    libjpegturbo
  LICENSE_FILES
    COPYRIGHT
  CMAKE_ARGS
    -DCMAKE_INSTALL_LIBDIR:STRING=lib
    -Dcxx:BOOL=OFF
    -Djbig:BOOL=OFF
    -Djpeg:BOOL=${libjpegturbo_enabled}
    -Dlerc:BOOL=OFF
    -Dlibdeflat:BOOL=OFF
    -Dlzma:BOOL=OFF
    -Dwebp:BOOL=OFF
    -Dzstd:BOOL=OFF
    -Dzlib:BOOL=${zlib_enabled}
    )
