# This file was generated by CMake because it detected TRY_RUN() commands
# in crosscompiling mode. It will be overwritten by the next CMake run.
# Copy it to a safe location, set the variables to appropriate values
# and use it then to preset the CMake cache (using -C).


# CMAKE_REQUIRE_LARGE_FILE_SUPPORT
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set CMAKE_REQUIRE_LARGE_FILE_SUPPORT to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# CMAKE_REQUIRE_LARGE_FILE_SUPPORT__TRYRUN_OUTPUT
#    contains the text the executable would have printed on stdout and stderr.
#    If the executable would not have been able to run, set CMAKE_REQUIRE_LARGE_FILE_SUPPORT__TRYRUN_OUTPUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The HAVE_CMAKE_REQUIRE_LARGE_FILE_SUPPORT variable holds the build result for this TRY_RUN().
#
# Source file   : /Builds/ParaView/devel/XSuperBuild/paraview/src/paraview-build/CMakeFiles/CMakeTmp/src.cxx
# Executable    : /Builds/ParaView/devel/XSuperBuild/paraview/src/paraview-build/CMakeFiles/cmTryCompileExec3603989475-CMAKE_REQUIRE_LARGE_FILE_SUPPORT
# Run arguments :
#    Called from: [1]	/Builds/ParaView/devel/XSuperBuild/paraview/src/paraview/VTK/CMakeLists.txt

SET( CMAKE_REQUIRE_LARGE_FILE_SUPPORT
"0"
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( CMAKE_REQUIRE_LARGE_FILE_SUPPORT__TRYRUN_OUTPUT
""
     CACHE STRING "Output from TRY_RUN" FORCE)


# VTK_TYPE_CHAR_IS_SIGNED
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set VTK_TYPE_CHAR_IS_SIGNED to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# The VTK_TYPE_CHAR_IS_SIGNED_COMPILED variable holds the build result for this TRY_RUN().
#
# Source file   : /Builds/ParaView/devel/XSuperBuild/paraview/src/paraview/VTK/CMake/vtkTestCharSignedness.cxx
# Executable    : /Builds/ParaView/devel/XSuperBuild/paraview/src/paraview-build/CMakeFiles/cmTryCompileExec2043748212-VTK_TYPE_CHAR_IS_SIGNED
# Run arguments :
#    Called from: [2]	/Builds/ParaView/devel/XSuperBuild/paraview/src/paraview/VTK/CMake/vtkTestTypes.cmake
#                 [1]	/Builds/ParaView/devel/XSuperBuild/paraview/src/paraview/VTK/CMakeLists.txt

SET( VTK_TYPE_CHAR_IS_SIGNED
"1"
     CACHE STRING "Result from TRY_RUN" FORCE)


# VTK_ANSI_STREAM_EOF_RESULT
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set VTK_ANSI_STREAM_EOF_RESULT to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# The VTK_ANSI_STREAM_EOF_COMPILED variable holds the build result for this TRY_RUN().
#
# Source file   : /Builds/ParaView/devel/XSuperBuild/paraview/src/paraview-build/VTK/CMake/vtkTestStreamEOF.cxx
# Executable    : /Builds/ParaView/devel/XSuperBuild/paraview/src/paraview-build/CMakeFiles/cmTryCompileExec1281256607-VTK_ANSI_STREAM_EOF_RESULT
# Run arguments :
#    Called from: [2]	/Builds/ParaView/devel/XSuperBuild/paraview/src/paraview/VTK/CMake/vtkTestStreamsLibrary.cmake
#                 [1]	/Builds/ParaView/devel/XSuperBuild/paraview/src/paraview/VTK/CMakeLists.txt

SET( VTK_ANSI_STREAM_EOF_RESULT
"1"
     CACHE STRING "Result from TRY_RUN" FORCE)


# KWSYS_LFS_WORKS
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set KWSYS_LFS_WORKS to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# KWSYS_LFS_WORKS__TRYRUN_OUTPUT
#    contains the text the executable would have printed on stdout and stderr.
#    If the executable would not have been able to run, set KWSYS_LFS_WORKS__TRYRUN_OUTPUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The KWSYS_LFS_WORKS_COMPILED variable holds the build result for this TRY_RUN().
#
# Source file   : /Builds/ParaView/devel/XSuperBuild/paraview/src/paraview/VTK/Utilities/KWSys/vtksys/kwsysPlatformTestsCXX.cxx
# Executable    : /Builds/ParaView/devel/XSuperBuild/paraview/src/paraview-build/CMakeFiles/cmTryCompileExec2750754377-KWSYS_LFS_WORKS
# Run arguments :
#    Called from: [1]	/Builds/ParaView/devel/XSuperBuild/paraview/src/paraview/VTK/Utilities/KWSys/vtksys/CMakeLists.txt

SET( KWSYS_LFS_WORKS
"0"
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( KWSYS_LFS_WORKS__TRYRUN_OUTPUT
""
     CACHE STRING "Output from TRY_RUN" FORCE)


# KWSYS_CHAR_IS_SIGNED
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set KWSYS_CHAR_IS_SIGNED to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# KWSYS_CHAR_IS_SIGNED__TRYRUN_OUTPUT
#    contains the text the executable would have printed on stdout and stderr.
#    If the executable would not have been able to run, set KWSYS_CHAR_IS_SIGNED__TRYRUN_OUTPUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The KWSYS_CHAR_IS_SIGNED_COMPILED variable holds the build result for this TRY_RUN().
#
# Source file   : /Builds/ParaView/devel/XSuperBuild/paraview/src/paraview/VTK/Utilities/KWSys/vtksys/kwsysPlatformTestsCXX.cxx
# Executable    : /Builds/ParaView/devel/XSuperBuild/paraview/src/paraview-build/CMakeFiles/cmTryCompileExec1190306106-KWSYS_CHAR_IS_SIGNED
# Run arguments :
#    Called from: [1]	/Builds/ParaView/devel/XSuperBuild/paraview/src/paraview/VTK/Utilities/KWSys/vtksys/CMakeLists.txt

SET( KWSYS_CHAR_IS_SIGNED
"0"
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( KWSYS_CHAR_IS_SIGNED__TRYRUN_OUTPUT
""
     CACHE STRING "Output from TRY_RUN" FORCE)


# HDF5_PRINTF_LL_TEST_RUN
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set HDF5_PRINTF_LL_TEST_RUN to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# HDF5_PRINTF_LL_TEST_RUN__TRYRUN_OUTPUT
#    contains the text the executable would have printed on stdout and stderr.
#    If the executable would not have been able to run, set HDF5_PRINTF_LL_TEST_RUN__TRYRUN_OUTPUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The HDF5_PRINTF_LL_TEST_COMPILE variable holds the build result for this TRY_RUN().
#
# Source file   : /Builds/ParaView/devel/XSuperBuild/paraview/src/paraview/VTK/ThirdParty/hdf5/vtkhdf5/Resources/HDF5Tests.c
# Executable    : /Builds/ParaView/devel/XSuperBuild/paraview/src/paraview-build/CMakeFiles/cmTryCompileExec232487749-HDF5_PRINTF_LL_TEST_RUN
# Run arguments :
#    Called from: [2]	/Builds/ParaView/devel/XSuperBuild/paraview/src/paraview/VTK/ThirdParty/hdf5/vtkhdf5/ConfigureChecks.cmake
#                 [1]	/Builds/ParaView/devel/XSuperBuild/paraview/src/paraview/VTK/ThirdParty/hdf5/vtkhdf5/CMakeLists.txt

SET( HDF5_PRINTF_LL_TEST_RUN
"0"
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( HDF5_PRINTF_LL_TEST_RUN__TRYRUN_OUTPUT
"PRINTF_LL_WIDTH=[l]"
     CACHE STRING "Output from TRY_RUN" FORCE)


# H5_LDOUBLE_TO_INTEGER_WORKS_RUN
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set H5_LDOUBLE_TO_INTEGER_WORKS_RUN to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# H5_LDOUBLE_TO_INTEGER_WORKS_RUN__TRYRUN_OUTPUT
#    contains the text the executable would have printed on stdout and stderr.
#    If the executable would not have been able to run, set H5_LDOUBLE_TO_INTEGER_WORKS_RUN__TRYRUN_OUTPUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The H5_LDOUBLE_TO_INTEGER_WORKS_COMPILE variable holds the build result for this TRY_RUN().
#
# Source file   : /Builds/ParaView/devel/XSuperBuild/paraview/src/paraview/VTK/ThirdParty/hdf5/vtkhdf5/Resources/ConversionTests.c
# Executable    : /Builds/ParaView/devel/XSuperBuild/paraview/src/paraview-build/CMakeFiles/cmTryCompileExec1899339701-H5_LDOUBLE_TO_INTEGER_WORKS_RUN
# Run arguments :
#    Called from: [2]	/Builds/ParaView/devel/XSuperBuild/paraview/src/paraview/VTK/ThirdParty/hdf5/vtkhdf5/ConfigureChecks.cmake
#                 [1]	/Builds/ParaView/devel/XSuperBuild/paraview/src/paraview/VTK/ThirdParty/hdf5/vtkhdf5/CMakeLists.txt

SET( H5_LDOUBLE_TO_INTEGER_WORKS_RUN
"0"
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( H5_LDOUBLE_TO_INTEGER_WORKS_RUN__TRYRUN_OUTPUT
""
     CACHE STRING "Output from TRY_RUN" FORCE)


# H5_ULONG_TO_FLOAT_ACCURATE_RUN
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set H5_ULONG_TO_FLOAT_ACCURATE_RUN to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# H5_ULONG_TO_FLOAT_ACCURATE_RUN__TRYRUN_OUTPUT
#    contains the text the executable would have printed on stdout and stderr.
#    If the executable would not have been able to run, set H5_ULONG_TO_FLOAT_ACCURATE_RUN__TRYRUN_OUTPUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The H5_ULONG_TO_FLOAT_ACCURATE_COMPILE variable holds the build result for this TRY_RUN().
#
# Source file   : /Builds/ParaView/devel/XSuperBuild/paraview/src/paraview/VTK/ThirdParty/hdf5/vtkhdf5/Resources/ConversionTests.c
# Executable    : /Builds/ParaView/devel/XSuperBuild/paraview/src/paraview-build/CMakeFiles/cmTryCompileExec3488427874-H5_ULONG_TO_FLOAT_ACCURATE_RUN
# Run arguments :
#    Called from: [2]	/Builds/ParaView/devel/XSuperBuild/paraview/src/paraview/VTK/ThirdParty/hdf5/vtkhdf5/ConfigureChecks.cmake
#                 [1]	/Builds/ParaView/devel/XSuperBuild/paraview/src/paraview/VTK/ThirdParty/hdf5/vtkhdf5/CMakeLists.txt

SET( H5_ULONG_TO_FLOAT_ACCURATE_RUN
"0"
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( H5_ULONG_TO_FLOAT_ACCURATE_RUN__TRYRUN_OUTPUT
""
     CACHE STRING "Output from TRY_RUN" FORCE)


# H5_ULONG_TO_FP_BOTTOM_BIT_ACCURATE_RUN
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set H5_ULONG_TO_FP_BOTTOM_BIT_ACCURATE_RUN to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# H5_ULONG_TO_FP_BOTTOM_BIT_ACCURATE_RUN__TRYRUN_OUTPUT
#    contains the text the executable would have printed on stdout and stderr.
#    If the executable would not have been able to run, set H5_ULONG_TO_FP_BOTTOM_BIT_ACCURATE_RUN__TRYRUN_OUTPUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The H5_ULONG_TO_FP_BOTTOM_BIT_ACCURATE_COMPILE variable holds the build result for this TRY_RUN().
#
# Source file   : /Builds/ParaView/devel/XSuperBuild/paraview/src/paraview/VTK/ThirdParty/hdf5/vtkhdf5/Resources/ConversionTests.c
# Executable    : /Builds/ParaView/devel/XSuperBuild/paraview/src/paraview-build/CMakeFiles/cmTryCompileExec845825622-H5_ULONG_TO_FP_BOTTOM_BIT_ACCURATE_RUN
# Run arguments :
#    Called from: [2]	/Builds/ParaView/devel/XSuperBuild/paraview/src/paraview/VTK/ThirdParty/hdf5/vtkhdf5/ConfigureChecks.cmake
#                 [1]	/Builds/ParaView/devel/XSuperBuild/paraview/src/paraview/VTK/ThirdParty/hdf5/vtkhdf5/CMakeLists.txt

SET( H5_ULONG_TO_FP_BOTTOM_BIT_ACCURATE_RUN
"1"
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( H5_ULONG_TO_FP_BOTTOM_BIT_ACCURATE_RUN__TRYRUN_OUTPUT
""
     CACHE STRING "Output from TRY_RUN" FORCE)


# H5_FP_TO_ULLONG_ACCURATE_RUN
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set H5_FP_TO_ULLONG_ACCURATE_RUN to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# H5_FP_TO_ULLONG_ACCURATE_RUN__TRYRUN_OUTPUT
#    contains the text the executable would have printed on stdout and stderr.
#    If the executable would not have been able to run, set H5_FP_TO_ULLONG_ACCURATE_RUN__TRYRUN_OUTPUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The H5_FP_TO_ULLONG_ACCURATE_COMPILE variable holds the build result for this TRY_RUN().
#
# Source file   : /Builds/ParaView/devel/XSuperBuild/paraview/src/paraview/VTK/ThirdParty/hdf5/vtkhdf5/Resources/ConversionTests.c
# Executable    : /Builds/ParaView/devel/XSuperBuild/paraview/src/paraview-build/CMakeFiles/cmTryCompileExec1596031630-H5_FP_TO_ULLONG_ACCURATE_RUN
# Run arguments :
#    Called from: [2]	/Builds/ParaView/devel/XSuperBuild/paraview/src/paraview/VTK/ThirdParty/hdf5/vtkhdf5/ConfigureChecks.cmake
#                 [1]	/Builds/ParaView/devel/XSuperBuild/paraview/src/paraview/VTK/ThirdParty/hdf5/vtkhdf5/CMakeLists.txt

SET( H5_FP_TO_ULLONG_ACCURATE_RUN
"0"
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( H5_FP_TO_ULLONG_ACCURATE_RUN__TRYRUN_OUTPUT
""
     CACHE STRING "Output from TRY_RUN" FORCE)


# H5_FP_TO_ULLONG_RIGHT_MAXIMUM_RUN
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set H5_FP_TO_ULLONG_RIGHT_MAXIMUM_RUN to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# H5_FP_TO_ULLONG_RIGHT_MAXIMUM_RUN__TRYRUN_OUTPUT
#    contains the text the executable would have printed on stdout and stderr.
#    If the executable would not have been able to run, set H5_FP_TO_ULLONG_RIGHT_MAXIMUM_RUN__TRYRUN_OUTPUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The H5_FP_TO_ULLONG_RIGHT_MAXIMUM_COMPILE variable holds the build result for this TRY_RUN().
#
# Source file   : /Builds/ParaView/devel/XSuperBuild/paraview/src/paraview/VTK/ThirdParty/hdf5/vtkhdf5/Resources/ConversionTests.c
# Executable    : /Builds/ParaView/devel/XSuperBuild/paraview/src/paraview-build/CMakeFiles/cmTryCompileExec754178525-H5_FP_TO_ULLONG_RIGHT_MAXIMUM_RUN
# Run arguments :
#    Called from: [2]	/Builds/ParaView/devel/XSuperBuild/paraview/src/paraview/VTK/ThirdParty/hdf5/vtkhdf5/ConfigureChecks.cmake
#                 [1]	/Builds/ParaView/devel/XSuperBuild/paraview/src/paraview/VTK/ThirdParty/hdf5/vtkhdf5/CMakeLists.txt

SET( H5_FP_TO_ULLONG_RIGHT_MAXIMUM_RUN
"1"
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( H5_FP_TO_ULLONG_RIGHT_MAXIMUM_RUN__TRYRUN_OUTPUT
""
     CACHE STRING "Output from TRY_RUN" FORCE)


# H5_LDOUBLE_TO_UINT_ACCURATE_RUN
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set H5_LDOUBLE_TO_UINT_ACCURATE_RUN to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# H5_LDOUBLE_TO_UINT_ACCURATE_RUN__TRYRUN_OUTPUT
#    contains the text the executable would have printed on stdout and stderr.
#    If the executable would not have been able to run, set H5_LDOUBLE_TO_UINT_ACCURATE_RUN__TRYRUN_OUTPUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The H5_LDOUBLE_TO_UINT_ACCURATE_COMPILE variable holds the build result for this TRY_RUN().
#
# Source file   : /Builds/ParaView/devel/XSuperBuild/paraview/src/paraview/VTK/ThirdParty/hdf5/vtkhdf5/Resources/ConversionTests.c
# Executable    : /Builds/ParaView/devel/XSuperBuild/paraview/src/paraview-build/CMakeFiles/cmTryCompileExec1159922899-H5_LDOUBLE_TO_UINT_ACCURATE_RUN
# Run arguments :
#    Called from: [2]	/Builds/ParaView/devel/XSuperBuild/paraview/src/paraview/VTK/ThirdParty/hdf5/vtkhdf5/ConfigureChecks.cmake
#                 [1]	/Builds/ParaView/devel/XSuperBuild/paraview/src/paraview/VTK/ThirdParty/hdf5/vtkhdf5/CMakeLists.txt

SET( H5_LDOUBLE_TO_UINT_ACCURATE_RUN
"0"
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( H5_LDOUBLE_TO_UINT_ACCURATE_RUN__TRYRUN_OUTPUT
""
     CACHE STRING "Output from TRY_RUN" FORCE)


# H5_ULLONG_TO_LDOUBLE_PRECISION_RUN
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set H5_ULLONG_TO_LDOUBLE_PRECISION_RUN to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# H5_ULLONG_TO_LDOUBLE_PRECISION_RUN__TRYRUN_OUTPUT
#    contains the text the executable would have printed on stdout and stderr.
#    If the executable would not have been able to run, set H5_ULLONG_TO_LDOUBLE_PRECISION_RUN__TRYRUN_OUTPUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The H5_ULLONG_TO_LDOUBLE_PRECISION_COMPILE variable holds the build result for this TRY_RUN().
#
# Source file   : /Builds/ParaView/devel/XSuperBuild/paraview/src/paraview/VTK/ThirdParty/hdf5/vtkhdf5/Resources/ConversionTests.c
# Executable    : /Builds/ParaView/devel/XSuperBuild/paraview/src/paraview-build/CMakeFiles/cmTryCompileExec4227282030-H5_ULLONG_TO_LDOUBLE_PRECISION_RUN
# Run arguments :
#    Called from: [2]	/Builds/ParaView/devel/XSuperBuild/paraview/src/paraview/VTK/ThirdParty/hdf5/vtkhdf5/ConfigureChecks.cmake
#                 [1]	/Builds/ParaView/devel/XSuperBuild/paraview/src/paraview/VTK/ThirdParty/hdf5/vtkhdf5/CMakeLists.txt

SET( H5_ULLONG_TO_LDOUBLE_PRECISION_RUN
"0"
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( H5_ULLONG_TO_LDOUBLE_PRECISION_RUN__TRYRUN_OUTPUT
""
     CACHE STRING "Output from TRY_RUN" FORCE)


# H5_FP_TO_INTEGER_OVERFLOW_WORKS_RUN
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set H5_FP_TO_INTEGER_OVERFLOW_WORKS_RUN to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# H5_FP_TO_INTEGER_OVERFLOW_WORKS_RUN__TRYRUN_OUTPUT
#    contains the text the executable would have printed on stdout and stderr.
#    If the executable would not have been able to run, set H5_FP_TO_INTEGER_OVERFLOW_WORKS_RUN__TRYRUN_OUTPUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The H5_FP_TO_INTEGER_OVERFLOW_WORKS_COMPILE variable holds the build result for this TRY_RUN().
#
# Source file   : /Builds/ParaView/devel/XSuperBuild/paraview/src/paraview/VTK/ThirdParty/hdf5/vtkhdf5/Resources/ConversionTests.c
# Executable    : /Builds/ParaView/devel/XSuperBuild/paraview/src/paraview-build/CMakeFiles/cmTryCompileExec2976698072-H5_FP_TO_INTEGER_OVERFLOW_WORKS_RUN
# Run arguments :
#    Called from: [2]	/Builds/ParaView/devel/XSuperBuild/paraview/src/paraview/VTK/ThirdParty/hdf5/vtkhdf5/ConfigureChecks.cmake
#                 [1]	/Builds/ParaView/devel/XSuperBuild/paraview/src/paraview/VTK/ThirdParty/hdf5/vtkhdf5/CMakeLists.txt

SET( H5_FP_TO_INTEGER_OVERFLOW_WORKS_RUN
"0"
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( H5_FP_TO_INTEGER_OVERFLOW_WORKS_RUN__TRYRUN_OUTPUT
""
     CACHE STRING "Output from TRY_RUN" FORCE)


# H5_LDOUBLE_TO_LLONG_ACCURATE_RUN
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set H5_LDOUBLE_TO_LLONG_ACCURATE_RUN to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# H5_LDOUBLE_TO_LLONG_ACCURATE_RUN__TRYRUN_OUTPUT
#    contains the text the executable would have printed on stdout and stderr.
#    If the executable would not have been able to run, set H5_LDOUBLE_TO_LLONG_ACCURATE_RUN__TRYRUN_OUTPUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The H5_LDOUBLE_TO_LLONG_ACCURATE_COMPILE variable holds the build result for this TRY_RUN().
#
# Source file   : /Builds/ParaView/devel/XSuperBuild/paraview/src/paraview/VTK/ThirdParty/hdf5/vtkhdf5/Resources/ConversionTests.c
# Executable    : /Builds/ParaView/devel/XSuperBuild/paraview/src/paraview-build/CMakeFiles/cmTryCompileExec2436514072-H5_LDOUBLE_TO_LLONG_ACCURATE_RUN
# Run arguments :
#    Called from: [2]	/Builds/ParaView/devel/XSuperBuild/paraview/src/paraview/VTK/ThirdParty/hdf5/vtkhdf5/ConfigureChecks.cmake
#                 [1]	/Builds/ParaView/devel/XSuperBuild/paraview/src/paraview/VTK/ThirdParty/hdf5/vtkhdf5/CMakeLists.txt

SET( H5_LDOUBLE_TO_LLONG_ACCURATE_RUN
"0"
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( H5_LDOUBLE_TO_LLONG_ACCURATE_RUN__TRYRUN_OUTPUT
""
     CACHE STRING "Output from TRY_RUN" FORCE)


# H5_LLONG_TO_LDOUBLE_CORRECT_RUN
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set H5_LLONG_TO_LDOUBLE_CORRECT_RUN to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# H5_LLONG_TO_LDOUBLE_CORRECT_RUN__TRYRUN_OUTPUT
#    contains the text the executable would have printed on stdout and stderr.
#    If the executable would not have been able to run, set H5_LLONG_TO_LDOUBLE_CORRECT_RUN__TRYRUN_OUTPUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The H5_LLONG_TO_LDOUBLE_CORRECT_COMPILE variable holds the build result for this TRY_RUN().
#
# Source file   : /Builds/ParaView/devel/XSuperBuild/paraview/src/paraview/VTK/ThirdParty/hdf5/vtkhdf5/Resources/ConversionTests.c
# Executable    : /Builds/ParaView/devel/XSuperBuild/paraview/src/paraview-build/CMakeFiles/cmTryCompileExec1387675970-H5_LLONG_TO_LDOUBLE_CORRECT_RUN
# Run arguments :
#    Called from: [2]	/Builds/ParaView/devel/XSuperBuild/paraview/src/paraview/VTK/ThirdParty/hdf5/vtkhdf5/ConfigureChecks.cmake
#                 [1]	/Builds/ParaView/devel/XSuperBuild/paraview/src/paraview/VTK/ThirdParty/hdf5/vtkhdf5/CMakeLists.txt

SET( H5_LLONG_TO_LDOUBLE_CORRECT_RUN
"0"
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( H5_LLONG_TO_LDOUBLE_CORRECT_RUN__TRYRUN_OUTPUT
""
     CACHE STRING "Output from TRY_RUN" FORCE)


# H5_NO_ALIGNMENT_RESTRICTIONS_RUN
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set H5_NO_ALIGNMENT_RESTRICTIONS_RUN to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# H5_NO_ALIGNMENT_RESTRICTIONS_RUN__TRYRUN_OUTPUT
#    contains the text the executable would have printed on stdout and stderr.
#    If the executable would not have been able to run, set H5_NO_ALIGNMENT_RESTRICTIONS_RUN__TRYRUN_OUTPUT empty.
#    Otherwise check if the output is evaluated by the calling CMake code. If so,
#    check what the source file would have printed when called with the given arguments.
# The H5_NO_ALIGNMENT_RESTRICTIONS_COMPILE variable holds the build result for this TRY_RUN().
#
# Source file   : /Builds/ParaView/devel/XSuperBuild/paraview/src/paraview/VTK/ThirdParty/hdf5/vtkhdf5/Resources/ConversionTests.c
# Executable    : /Builds/ParaView/devel/XSuperBuild/paraview/src/paraview-build/CMakeFiles/cmTryCompileExec198524646-H5_NO_ALIGNMENT_RESTRICTIONS_RUN
# Run arguments :
#    Called from: [2]	/Builds/ParaView/devel/XSuperBuild/paraview/src/paraview/VTK/ThirdParty/hdf5/vtkhdf5/ConfigureChecks.cmake
#                 [1]	/Builds/ParaView/devel/XSuperBuild/paraview/src/paraview/VTK/ThirdParty/hdf5/vtkhdf5/CMakeLists.txt

SET( H5_NO_ALIGNMENT_RESTRICTIONS_RUN
"0"
     CACHE STRING "Result from TRY_RUN" FORCE)

SET( H5_NO_ALIGNMENT_RESTRICTIONS_RUN__TRYRUN_OUTPUT
""
     CACHE STRING "Output from TRY_RUN" FORCE)
