superbuild_add_project(genericio
  DEPENDS mpi
  DEPENDS_OPTIONAL cxx11
  LICENSE_FILES
    LICENSE
  CMAKE_ARGS
    -DBUILD_SHARED_LIBS:BOOL=OFF
    -DBUILD_TESTING:BOOL=OFF
    -DBUILD_PROGRAMS:BOOL=OFF)
