set( CMAKE_REQUIRE_LARGE_FILE_SUPPORT_COMPILED TRUE
     CACHE INTERNAL "Result from TRY_COMPILE" FORCE)
set( CMAKE_REQUIRE_LARGE_FILE_SUPPORT 0
     CACHE INTERNAL "Result from TRY_RUN" FORCE)
set( CMAKE_REQUIRE_LARGE_FILE_SUPPORT__TRYRUN_OUTPUT ""
     CACHE INTERNAL "Output from TRY_RUN" FORCE)

set( NO_ICC_IDYNAMIC_NEEDED_COMPILED TRUE
     CACHE INTERNAL "Result from TRY_COMPILE" FORCE)
set( NO_ICC_IDYNAMIC_NEEDED 1
     CACHE INTERNAL "Result from TRY_RUN" FORCE) 
set( NO_ICC_IDYNAMIC_NEEDED__TRYRUN_OUTPUT ""
     CACHE INTERNAL "Output from TRY_RUN" FORCE) 

set( KWSYS_LFS_WORKS_COMPILED TRUE
     CACHE INTERNAL "Result from TRY_COMPILE" FORCE)
set( KWSYS_LFS_WORKS 0
     CACHE INTERNAL "Result from TRY_RUN" FORCE)
set( KWSYS_LFS_WORKS__TRYRUN_OUTPUT ""
     CACHE INTERNAL "Output from TRY_RUN" FORCE)
