set(DOUBLE_IS_LITTLE_ENDIAN_IEEE754_COMPILED TRUE
    CACHE INTERNAL "Result of TRY_COMPILE" FORCE)
set(DOUBLE_IS_LITTLE_ENDIAN_IEEE754 0
    CACHE INTERNAL "Result of TRY_RUN" FORCE)

set(DOUBLE_IS_BIG_ENDIAN_IEEE754_COMPILED TRUE
    CACHE INTERNAL "Result of TRY_COMPILE" FORCE)
set(DOUBLE_IS_BIG_ENDIAN_IEEE754 1
    CACHE INTERNAL "Result of TRY_RUN" FORCE)

set(DOUBLE_IS_ARM_MIXED_ENDIAN_IEEE754_COMPILED TRUE
    CACHE INTERNAL "Result of TRY_COMPILE" FORCE)
set(DOUBLE_IS_ARM_MIXED_ENDIAN_IEEE754 1
    CACHE INTERNAL "Result of TRY_RUN" FORCE)

set(X87_DOUBLE_ROUNDING_COMPILED TRUE
    CACHE INTERNAL "Result of TRY_COMPILE" FORCE)
set(X87_DOUBLE_ROUNDING 0
    CACHE INTERNAL "Result of TRY_RUN" FORCE)

set(TANH_PRESERVES_ZERO_SIGN_COMPILED TRUE
    CACHE INTERNAL "Result of TRY_COMPILE" FORCE)
set(TANH_PRESERVES_ZERO_SIGN 0
    CACHE INTERNAL "Result of TRY_RUN" FORCE)

set(POSIX_SEMAPHORES_NOT_ENABLED_COMPILED TRUE
    CACHE INTERNAL "Result of TRY_COMPILE" FORCE)
set(POSIX_SEMAPHORES_NOT_ENABLED 0
    CACHE INTERNAL "Result of TRY_RUN" FORCE)

set(HAVE_BROKEN_SEM_GETVALUE_COMPILED TRUE
    CACHE INTERNAL "Result of TRY_COMPILE" FORCE)
set(HAVE_BROKEN_SEM_GETVALUE 0
    CACHE INTERNAL "Result of TRY_RUN" FORCE)

set(HAVE_BROKEN_NICE_EXITCODE_COMPILED TRUE
    CACHE INTERNAL "Result of TRY_COMPILE" FORCE)
set(HAVE_BROKEN_NICE_EXITCODE 1
    CACHE INTERNAL "Result of TRY_RUN" FORCE)

set(HAVE_BROKEN_POLL_EXITCODE_COMPILED TRUE
    CACHE INTERNAL "Result of TRY_COMPILE" FORCE)
set(HAVE_BROKEN_POLL_EXITCODE 1
    CACHE INTERNAL "Result of TRY_RUN" FORCE)

set(HAVE_WORKING_TZSET_COMPILED TRUE
    CACHE INTERNAL "Result of TRY_COMPILE" FORCE)
set(HAVE_WORKING_TZSET 0
    CACHE INTERNAL "Result of TRY_RUN" FORCE)

set(HAVE_LONG_LONG_FORMAT_COMPILED TRUE
    CACHE INTERNAL "Result of TRY_COMPILE" FORCE)
set(HAVE_LONG_LONG_FORMAT 0
    CACHE INTERNAL "Result of TRY_RUN" FORCE)

set(HAVE_SIZE_T_FORMAT_COMPILED TRUE
    CACHE INTERNAL "Result of TRY_COMPILE" FORCE)
set(HAVE_SIZE_T_FORMAT 0
    CACHE INTERNAL "Result of TRY_RUN" FORCE)
