
add_external_project(boost
  DEPENDS zlib
  URL "http://www.vtk.org/files/support/boost-1.45.0-cmake.tar.gz"
  URL_MD5 1e506d26d8a74fa46050ab0ce19101cd
  CMAKE_ARGS
    -DBUILD_EXAMPLES:BOOL=OFF
    -DBUILD_TESTING:BOOL=OFF
    -DBUILD_VERSIONED:BOOL=OFF
    -DENABLE_STATIC:BOOL=OFF
    -DINSTALL_VERSIONED:BOOL=OFF
    -DWINMANGLE_LIBNAMES:BOOL=ON
    -DWITH_BZIP2:BOOL=OFF
    -DWITH_DOXYGEN:BOOL=OFF
    -DWITH_EXPAT:BOOL=OFF
    -DWITH_ICU:BOOL=OFF
    -DWITH_MPI:BOOL=OFF
    -DWITH_PYTHON:BOOL=OFF
    -DWITH_XSLTPROC:BOLL=OFF
)
