add_external_project(
  hdf5
  DEPENDS zlib szip
  CMAKE_ARGS
    -DBUILD_SHARED_LIBS:BOOL=TRUE
    -DHDF5_ENABLE_Z_LIB_SUPPORT:BOOL=TRUE
    -DHDF5_ENABLE_SZIP_SUPPORT:BOOL=TRUE
    -DHDF5_ENABLE_SZIP_ENCODING:BOOL=TRUE
    -DSZIP_LIBRARY:FILEPATH=<INSTALL_DIR>/lib/libsz.so
    -DSZIP_INCLUDE_DIR:FILEPATH=<INSTALL_DIR>/include
)
