set(USE_NONFREE_COMPONENTS          ON CACHE BOOL "")
set(BUILD_TESTING                   ON CACHE BOOL "")
set(GENERATE_SPDX                   ON CACHE BOOL "")

if ("$ENV{CMAKE_CONFIGURATION}" MATCHES "linux")
  set(FILE_COMMAND "/usr/bin/file" CACHE FILEPATH "")
endif ()

# The new Mesa has issues with back screens when rendering. See
# paraview/paraview#22152.
set(mesa_SOURCE_SELECTION "21.2.1" CACHE STRING "")

# Build LLVM as static to reduce the number of shared libraries needed.
set(llvm_BUILD_SHARED_LIBS "OFF" CACHE STRING "")

function (suppress_project name)
  set("SUPPRESS_${name}_OUTPUT" ON CACHE BOOL "")
endfunction ()

function (enable_project name)
  set("ENABLE_${name}" ON CACHE BOOL "")
  suppress_project("${name}")
endfunction ()

enable_project(adios2)
enable_project(alembic)
enable_project(blosc)
enable_project(cosmotools)
enable_project(exodus) # requires seacas to actually build anything
enable_project(ffmpeg)
enable_project(fortran)
enable_project(gdal)
enable_project(gmsh)
enable_project(h5py)
enable_project(launchers)
enable_project(matplotlib)
enable_project(medreader)
enable_project(mesa)
enable_project(mili)
enable_project(mpi)
enable_project(netcdf)
enable_project(nlohmannjson)
enable_project(numpy)
enable_project(nvidiaindex)
enable_project(occt)
enable_project(openimagedenoise)
enable_project(openmp)
enable_project(openpmd)
enable_project(openvdb)
enable_project(ospray)
enable_project(ospraymaterials)
enable_project(ospraymodulempi)
enable_project(paraview)
enable_project(paraviewgettingstartedguide)
enable_project(paraviewpluginsexternal)
enable_project(paraviewtutorialdata)
enable_project(paraviewweb)
enable_project(pdal)
enable_project(python3)
enable_project(pythonmpi4py)
enable_project(pythonnetcdf4)
enable_project(pythonpandas)
enable_project(pythonpygments)
enable_project(qt5)
enable_project(scipy)
enable_project(seacas) # needed to actually build exodus
enable_project(silo)
enable_project(surfacetrackercut)
enable_project(sympy)
enable_project(szip)
enable_project(tbb)
enable_project(ttk)
enable_project(visitbridge)
enable_project(vortexfinder2)
enable_project(vrpn)
enable_project(vtkm)
enable_project(xdmf3)
enable_project(xerces)
enable_project(zfp)

set(ENABLE_egl                      OFF CACHE BOOL "")
set(ENABLE_osmesa                   OFF CACHE BOOL "")
set(ENABLE_paraviewsdk              OFF CACHE BOOL "")
# needs cuda
set(ENABLE_visrtx                   OFF CACHE BOOL "")

# qt5 things
set(qt5_SOURCE_SELECTION            "5.15" CACHE STRING "")

# output suppressions
suppress_project(boost)
suppress_project(bzip2)
suppress_project(curl)
suppress_project(embree)
suppress_project(expat)
suppress_project(ffi)
suppress_project(fontconfig)
suppress_project(freetype)
suppress_project(genericio)
suppress_project(geotiff)
suppress_project(glproto)
suppress_project(gperf)
suppress_project(hdf5)
suppress_project(imath)
suppress_project(ispc)
suppress_project(jsonc)
suppress_project(jsoncpp)
suppress_project(lapack)
suppress_project(libjpegturbo)
suppress_project(libusb)
suppress_project(libxml2)
suppress_project(llvm)
suppress_project(lookingglass)
suppress_project(medconfiguration)
suppress_project(medcoupling)
suppress_project(medfile)
suppress_project(mesa)
suppress_project(meson)
suppress_project(mili)
suppress_project(nvidiamdl)
suppress_project(nvidiaoptix)
suppress_project(openvkl)
suppress_project(openxrsdk)
suppress_project(osmesa)
suppress_project(paraviewwebdivvy)
suppress_project(paraviewwebglance)
suppress_project(paraviewweblite)
suppress_project(paraviewwebvisualizer)
suppress_project(pkgconf)
suppress_project(png)
suppress_project(proj)
suppress_project(pybind11)
suppress_project(pythonaiohttp)
suppress_project(pythonaiosignal)
suppress_project(pythonasynctimeout)
suppress_project(pythonattrs)
suppress_project(pythonbeniget)
suppress_project(pythoncffi)
suppress_project(pythoncftime)
suppress_project(pythonchardet)
suppress_project(pythoncharsetnormalizer)
suppress_project(pythoncppy)
suppress_project(pythoncycler)
suppress_project(pythoncython)
suppress_project(pythondateutil)
suppress_project(pythonflitcore)
suppress_project(pythonfonttools)
suppress_project(pythonfrozenlist)
suppress_project(pythongast)
suppress_project(pythonhatchfancypypireadme)
suppress_project(pythonhatchling)
suppress_project(pythonhatchvcs)
suppress_project(pythonidna)
suppress_project(pythonkiwisolver)
suppress_project(pythonmako)
suppress_project(pythonmarkupsafe)
suppress_project(pythonmesonpython)
suppress_project(pythonmpmath)
suppress_project(pythonmultidict)
suppress_project(pythonpackaging)
suppress_project(pythonpandas)
suppress_project(pythonpathspec)
suppress_project(pythonpillow)
suppress_project(pythonpkgconfig)
suppress_project(pythonpluggy)
suppress_project(pythonply)
suppress_project(pythonpycparser)
suppress_project(pythonpygments)
suppress_project(pythonpyparsing)
suppress_project(pythonpyprojectmetadata)
suppress_project(pythonpythran)
suppress_project(pythonsemanticversion)
suppress_project(pythonsetuptools)
suppress_project(pythonsetuptoolsrust)
suppress_project(pythonsetuptoolsscm)
suppress_project(pythonsix)
suppress_project(pythontoml)
suppress_project(pythontomli)
suppress_project(pythontroveclassifiers)
suppress_project(pythontypingextensions)
suppress_project(pythontzdata)
suppress_project(pythonversioneer)
suppress_project(pythonwheel)
suppress_project(pythonwslinkasync)
suppress_project(pythonyarl)
suppress_project(pytz)
suppress_project(qhull)
suppress_project(rapidjson)
suppress_project(rkcommon)
suppress_project(snappy)
suppress_project(sqlite)
suppress_project(tiff)
suppress_project(utillinux)
suppress_project(visrtx)
suppress_project(xz)
suppress_project(zeromq)
suppress_project(zlib)
suppress_project(zstd)

if ("$ENV{CI_COMMIT_TITLE}" MATCHES "^paraview: add release v\(.*\)$")
  set(paraview_SOURCE_SELECTION           "${CMAKE_MATCH_1}" CACHE STRING "")
else ()
  set(paraview_SOURCE_SELECTION           "source" CACHE STRING "")
  file(TO_CMAKE_PATH "$ENV{CI_PROJECT_DIR}/source-paraview" paraview_source_dir)
  set(paraview_SOURCE_DIR                 "${paraview_source_dir}" CACHE PATH "")
endif ()

# Default to Release builds.
if ("$ENV{CMAKE_BUILD_TYPE}" STREQUAL "")
  set(CMAKE_BUILD_TYPE "Release" CACHE STRING "")
else ()
  set(CMAKE_BUILD_TYPE "$ENV{CMAKE_BUILD_TYPE}" CACHE STRING "")
endif ()

include("${CMAKE_CURRENT_LIST_DIR}/configure_cache.cmake")
