set(USE_NONFREE_COMPONENTS          ON CACHE BOOL "")
set(BUILD_TESTING                   ON CACHE BOOL "")

function (enable_project name)
  set("ENABLE_${name}" ON CACHE BOOL "")
  set("SUPPRESS_${name}_OUTPUT" ON CACHE BOOL "")
endfunction ()

enable_project(adios2)
enable_project(cosmotools)
enable_project(ffmpeg)
enable_project(fortran)
enable_project(gdal)
enable_project(gmsh)
enable_project(h5py)
enable_project(launchers)
enable_project(matplotlib)
enable_project(mesa)
enable_project(mili)
enable_project(mpi)
enable_project(netcdf)
enable_project(nlohmannjson)
enable_project(numpy)
enable_project(nvidiaindex)
enable_project(openimagedenoise)
enable_project(openpmd)
enable_project(ospray)
enable_project(ospraymaterials)
enable_project(ospraymodulempi)
enable_project(paraview)
enable_project(paraviewgettingstartedguide)
enable_project(paraviewpluginsexternal)
enable_project(paraviewtutorialdata)
enable_project(paraviewweb)
enable_project(python3)
enable_project(pythonpandas)
enable_project(pythonpygments)
enable_project(qt5)
enable_project(scipy)
enable_project(silo)
enable_project(surfacetrackercut)
enable_project(szip)
enable_project(tbb)
enable_project(ttk)
enable_project(visitbridge)
enable_project(vortexfinder2)
enable_project(vrpn)
enable_project(vtkm)
enable_project(xdmf3)
enable_project(zfp)

set(ENABLE_egl                      OFF CACHE BOOL "")
set(ENABLE_osmesa                   OFF CACHE BOOL "")
set(ENABLE_paraviewsdk              OFF CACHE BOOL "")
# needs cuda
set(ENABLE_visrtx                   OFF CACHE BOOL "")

# qt5 things
set(qt5_SOURCE_SELECTION            "5.12" CACHE STRING "")
# the gold linker seems to fail with internal error on centos7 builds
# disabling
set(qt5_EXTRA_CONFIGURATION_OPTIONS "-no-use-gold-linker" CACHE STRING "")

# output suppressions
set(SUPPRESS_boost_OUTPUT               ON CACHE BOOL "")
set(SUPPRESS_embree_OUTPUT              ON CACHE BOOL "")
set(SUPPRESS_freetype_OUTPUT            ON CACHE BOOL "")
set(SUPPRESS_hdf5_OUTPUT                ON CACHE BOOL "")
set(SUPPRESS_lapack_OUTPUT              ON CACHE BOOL "")
set(SUPPRESS_openvkl_OUTPUT             ON CACHE BOOL "")
set(SUPPRESS_pybind11_OUTPUT            ON CACHE BOOL "")
set(SUPPRESS_pythonzope_OUTPUT          ON CACHE BOOL "")
set(SUPPRESS_pythonzopeinterface_OUTPUT ON CACHE BOOL "")

if ("$ENV{CI_COMMIT_TITLE}" MATCHES "^paraview: add release v\(.*\)$")
  set(paraview_SOURCE_SELECTION           "${CMAKE_MATCH_1}" CACHE STRING "")
else ()
  set(paraview_SOURCE_SELECTION           "source" CACHE STRING "")
  file(TO_CMAKE_PATH "$ENV{CI_PROJECT_DIR}/source-paraview" paraview_source_dir)
  set(paraview_SOURCE_DIR                 "${paraview_source_dir}" CACHE PATH "")
endif ()

# Default to Release builds.
if ("$ENV{CMAKE_BUILD_TYPE}" STREQUAL "")
  set(CMAKE_BUILD_TYPE "Release" CACHE STRING "")
else ()
  set(CMAKE_BUILD_TYPE "$ENV{CMAKE_BUILD_TYPE}" CACHE STRING "")
endif ()

include("${CMAKE_CURRENT_LIST_DIR}/configure_sccache.cmake")
